#!/bin/bash

rm -f tmp/a_dlink.reg.c
gcc -D__CUDA_ARCH__=800 -D__CUDA_ARCH_LIST__=800 -E -x c++  -DCUDA_DOUBLE_MATH_FUNCTIONS -D__CUDACC__ -D__NVCC__  "-I/sw/pkgs/arc/cuda/11.8.0/bin/../targets/x86_64-linux/include"    -D__CUDACC_VER_MAJOR__=11 -D__CUDACC_VER_MINOR__=8 -D__CUDACC_VER_BUILD__=89 -D__CUDA_API_VER_MAJOR__=11 -D__CUDA_API_VER_MINOR__=8 -D__NVCC_DIAG_PRAGMA_SUPPORT__=1 -include "cuda_runtime.h" -m64 "../sgemm.cu" -o "tmp/sgemm.cpp1.ii"
cicc --c++14 --gnu_version=80500 --display_error_number --orig_src_file_name "sgemm.cu" --orig_src_path_name "/home/abagali/570/SGEMM_CUDA/sgemm.cu" --allow_managed   -arch compute_80 -show-src -m64 --no-version-ident -ftz=0 -prec_div=1 -prec_sqrt=1 -fmad=1 --include_file_name "sgemm.fatbin.c" -tused --gen_module_id_file --module_id_file_name "tmp/sgemm.module_id" --gen_c_file_name "tmp/sgemm.cudafe1.c" --stub_file_name "tmp/sgemm.cudafe1.stub.c" --gen_device_file_name "tmp/sgemm.cudafe1.gpu"  "tmp/sgemm.cpp1.ii" -o "tmp/sgemm.ptx"
ptxas -arch=sm_80 -m64  "tmp/sgemm.ptx"  -o "tmp/sgemm.sm_80.cubin"
fatbinary --create="tmp/sgemm.fatbin" -64 --cicc-cmdline="-ftz=0 -prec_div=1 -prec_sqrt=1 -fmad=1 " "--image3=kind=elf,sm=80,file=tmp/sgemm.sm_80.cubin" "--image3=kind=ptx,sm=80,file=tmp/sgemm.ptx" --embedded-fatbin="tmp/sgemm.fatbin.c"
gcc -D__CUDA_ARCH_LIST__=800 -E -x c++ -D__CUDACC__ -D__NVCC__  "-I/sw/pkgs/arc/cuda/11.8.0/bin/../targets/x86_64-linux/include"    -D__CUDACC_VER_MAJOR__=11 -D__CUDACC_VER_MINOR__=8 -D__CUDACC_VER_BUILD__=89 -D__CUDA_API_VER_MAJOR__=11 -D__CUDA_API_VER_MINOR__=8 -D__NVCC_DIAG_PRAGMA_SUPPORT__=1 -include "cuda_runtime.h" -m64 "../sgemm.cu" -o "tmp/sgemm.cpp4.ii"
cudafe++ --c++14 --gnu_version=80500 --display_error_number --orig_src_file_name "../sgemm.cu" --orig_src_path_name "/home/abagali/570/SGEMM_CUDA/sgemm.cu" --allow_managed  --m64 --parse_templates --gen_c_file_name "tmp/sgemm.cudafe1.cpp" --stub_file_name "sgemm.cudafe1.stub.c" --module_id_file_name "tmp/sgemm.module_id" "tmp/sgemm.cpp4.ii"
gcc -D__CUDA_ARCH__=800 -D__CUDA_ARCH_LIST__=800 -c -x c++  -DCUDA_DOUBLE_MATH_FUNCTIONS "-I/sw/pkgs/arc/cuda/11.8.0/bin/../targets/x86_64-linux/include"   -m64 "tmp/sgemm.cudafe1.cpp" -o "tmp/sgemm.o"
gcc -D__CUDA_ARCH__=800 -D__CUDA_ARCH_LIST__=800 -E -x c++  -DCUDA_DOUBLE_MATH_FUNCTIONS -D__CUDACC__ -D__NVCC__  "-I/sw/pkgs/arc/cuda/11.8.0/bin/../targets/x86_64-linux/include"    -D__CUDACC_VER_MAJOR__=11 -D__CUDACC_VER_MINOR__=8 -D__CUDACC_VER_BUILD__=89 -D__CUDA_API_VER_MAJOR__=11 -D__CUDA_API_VER_MINOR__=8 -D__NVCC_DIAG_PRAGMA_SUPPORT__=1 -include "cuda_runtime.h" -m64 "../src/kernels.cu" -o "tmp/kernels.cpp1.ii"

cicc --c++14 --gnu_version=80500 --display_error_number --orig_src_file_name "src/kernels.cu" --orig_src_path_name "/home/abagali/570/SGEMM_CUDA/src/kernels.cu" --allow_managed   -arch compute_80 -show-src -m64 --no-version-ident -ftz=0 -prec_div=1 -prec_sqrt=1 -fmad=1 --include_file_name "kernels.fatbin.c" -tused --gen_module_id_file --module_id_file_name "tmp/kernels.module_id" --gen_c_file_name "tmp/kernels.cudafe1.c" --stub_file_name "tmp/kernels.cudafe1.stub.c" --gen_device_file_name "tmp/kernels.cudafe1.gpu"  "tmp/kernels.cpp1.ii" -o "tmp/kernels.ptx"
cp ../build_ir/sgemm_device.ptx tmp/kernels.ptx
ptxas -arch=sm_80 -m64  "tmp/kernels.ptx"  -o "tmp/kernels.sm_80.cubin"
fatbinary --create="tmp/kernels.fatbin" -64 --cicc-cmdline="-ftz=0 -prec_div=1 -prec_sqrt=1 -fmad=1 " "--image3=kind=elf,sm=80,file=tmp/kernels.sm_80.cubin" "--image3=kind=ptx,sm=80,file=tmp/kernels.ptx" --embedded-fatbin="tmp/kernels.fatbin.c"
gcc -D__CUDA_ARCH_LIST__=800 -E -x c++ -D__CUDACC__ -D__NVCC__  "-I/sw/pkgs/arc/cuda/11.8.0/bin/../targets/x86_64-linux/include"    -D__CUDACC_VER_MAJOR__=11 -D__CUDACC_VER_MINOR__=8 -D__CUDACC_VER_BUILD__=89 -D__CUDA_API_VER_MAJOR__=11 -D__CUDA_API_VER_MINOR__=8 -D__NVCC_DIAG_PRAGMA_SUPPORT__=1 -include "cuda_runtime.h" -m64 "../src/kernels.cu" -o "tmp/kernels.cpp4.ii"

cudafe++ --c++14 --gnu_version=80500 --display_error_number --orig_src_file_name "../src/kernels.cu" --orig_src_path_name "/home/abagali/570/SGEMM_CUDA/src/kernels.cu" --allow_managed  --m64 --parse_templates --gen_c_file_name "tmp/kernels.cudafe1.cpp" --stub_file_name "kernels.cudafe1.stub.c" --module_id_file_name "tmp/kernels.module_id" "tmp/kernels.cpp4.ii"
gcc -D__CUDA_ARCH__=800 -D__CUDA_ARCH_LIST__=800 -c -x c++  -DCUDA_DOUBLE_MATH_FUNCTIONS "-I/sw/pkgs/arc/cuda/11.8.0/bin/../targets/x86_64-linux/include"   -m64 "tmp/kernels.cudafe1.cpp" -o "tmp/kernels.o"
nvlink -m64 --arch=sm_80 --register-link-binaries="tmp/a_dlink.reg.c"    "-L/sw/pkgs/arc/cuda/11.8.0/bin/../targets/x86_64-linux/lib/stubs" "-L/sw/pkgs/arc/cuda/11.8.0/bin/../targets/x86_64-linux/lib" -cpu-arch=X86_64 "tmp/sgemm.o" "tmp/kernels.o"  -lcudadevrt  -o "tmp/a_dlink.sm_80.cubin" --host-ccbin "gcc"
fatbinary --create="tmp/a_dlink.fatbin" -64 --cicc-cmdline="-ftz=0 -prec_div=1 -prec_sqrt=1 -fmad=1 " -link "--image3=kind=elf,sm=80,file=tmp/a_dlink.sm_80.cubin" --embedded-fatbin="tmp/a_dlink.fatbin.c"
gcc -D__CUDA_ARCH_LIST__=800 -c -x c++ -DFATBINFILE="\"tmp/a_dlink.fatbin.c\"" -DREGISTERLINKBINARYFILE="\"tmp/a_dlink.reg.c\"" -I. -D__NV_EXTRA_INITIALIZATION= -D__NV_EXTRA_FINALIZATION= -D__CUDA_INCLUDE_COMPILER_INTERNAL_HEADERS__  "-I/sw/pkgs/arc/cuda/11.8.0/bin/../targets/x86_64-linux/include"    -D__CUDACC_VER_MAJOR__=11 -D__CUDACC_VER_MINOR__=8 -D__CUDACC_VER_BUILD__=89 -D__CUDA_API_VER_MAJOR__=11 -D__CUDA_API_VER_MINOR__=8 -D__NVCC_DIAG_PRAGMA_SUPPORT__=1 -m64 "/sw/pkgs/arc/cuda/11.8.0/bin/crt/link.stub" -o "tmp/a_dlink.o"
g++ -D__CUDA_ARCH_LIST__=800 -m64 -Wl,--start-group "tmp/a_dlink.o" "tmp/sgemm.o" "tmp/kernels.o"   "-L/sw/pkgs/arc/cuda/11.8.0/bin/../targets/x86_64-linux/lib/stubs" "-L/sw/pkgs/arc/cuda/11.8.0/bin/../targets/x86_64-linux/lib"  -lcudadevrt  -lcudart_static  -lrt -lpthread  -ldl  -Wl,--end-group -o "sgemm_opt.out"